Repository BSData/adeptus-titanicus, pull requests merged in 2021-11, with the labels that each got.

#150 Updated ReadMe file
  README.md
Labels: enhancement

#153 Minorfixes
  Adeptus Titanicus 2018.gst
Labels: bug, enhancement, Battlegroup

#155 Tempestus traitorbook
  Adeptus Titanicus 2018.gst
Labels: enhancement, Battlegroup

#157 Mortis traitor book
  Adeptus Titanicus 2018.gst
Labels: enhancement

#161 Fureans traitor book
  Adeptus Titanicus 2018.gst
Labels: enhancement

#164 Vulpa traitor book
  Adeptus Titanicus 2018.gst
Labels: enhancement

#166 Legio vulcanum traitor book
  Adeptus Titanicus 2018.gst
Labels: enhancement

#169 Traitor wargear
  Adeptus Titanicus 2018.gst
Labels: bug, enhancement

#171 Infernus traitor book
  Adeptus Titanicus 2018.gst
Labels: enhancement

#175 Audax traitor book
  Adeptus Titanicus 2018.gst
Labels: enhancement

#182 Legio laniskara traitor
  Adeptus Titanicus 2018.gst
Labels: enhancement

#145 fix for issue 140 v2
  Battlegroup.cat
Labels: enhancement
